'use client'

import { useState } from 'react'
import { ArrowLeft, Check, FileArchive, FileImage, FileText, Film, LoaderCircle, RefreshCw, UploadCloud, WandSparkles } from 'lucide-react'
import Link from 'next/link'

const tools = [{ name: 'Convert files', description: 'Change files between popular formats.', icon: RefreshCw, options: ['PDF', 'DOCX', 'JPG', 'PNG', 'WebP'] }, { name: 'Edit images', description: 'Crop, resize, compress, and enhance images.', icon: FileImage, options: ['Crop', 'Resize', 'Compress', 'Enhance'] }, { name: 'Edit documents', description: 'Merge, split, and clean up documents.', icon: FileText, options: ['Merge PDF', 'Split PDF', 'Compress PDF', 'Extract pages'] }, { name: 'Video tools', description: 'Trim clips and export lightweight previews.', icon: Film, options: ['Trim', 'Compress', 'Extract audio', 'GIF'] }]

export default function ToolsPage() {
  const [active, setActive] = useState(0); const [running, setRunning] = useState(false); const [done, setDone] = useState(false)
  const run = () => { setRunning(true); setDone(false); setTimeout(() => { setRunning(false); setDone(true) }, 1800) }
  const ToolIcon = tools[active].icon
  return <main className="tools-page"><header className="tools-header"><Link href="/" className="back-link"><ArrowLeft size={15} /> Back to workspace</Link><div className="auth-brand"><div className="logo-mark"><span /></div><span>ZFile Studio</span></div><span className="eyebrow">Demo workspace</span></header><section className="tools-hero"><div className="tool-hero-icon"><WandSparkles size={21} /></div><p className="eyebrow">File operations</p><h1>Make every file ready.</h1><p className="subtitle">Convert and edit files with a focused, secure workflow.</p></section><div className="tools-layout"><nav className="tools-list">{tools.map((tool, index) => { const Icon = tool.icon; return <button key={tool.name} className={`tool-card ${active === index ? 'tool-card-active' : ''}`} onClick={() => { setActive(index); setDone(false) }}><Icon size={19} /><span><b>{tool.name}</b><small>{tool.description}</small></span></button> })}</nav><section className="tool-panel"><div className="tool-panel-head"><div className="tool-panel-title"><ToolIcon size={18} /><div><p className="eyebrow">Selected workflow</p><h2>{tools[active].name}</h2></div></div><span className="demo-badge">Demo</span></div><div className="tool-drop"><div className="drop-icon">{done ? <Check size={22} /> : <UploadCloud size={22} />}</div><h3>{done ? 'Ready to download' : 'Drop a file here'}</h3><p>{done ? 'Your demo operation finished successfully.' : 'or choose a file from your device'}</p><button className="secondary-button"><FileArchive size={15} /> Choose file</button></div><div className="tool-options"><p className="eyebrow">Output options</p><div className="option-chips">{tools[active].options.map((option, index) => <button className={`option-chip ${index === 0 ? 'option-selected' : ''}`} key={option}>{option}</button>)}</div></div><button className="primary-button run-button" onClick={run} disabled={running}>{running ? <><LoaderCircle className="spin" size={15} /> Processing securely...</> : done ? <>Download result <Check size={15} /></> : <>Run {tools[active].name} <RefreshCw size={15} /></>}</button></section></div></main>
}
